const currencies = {
  'CAD': 'CAD: Canadian Dollar',
  'BGN': 'BGN: Bulgurian Lev',
  'BRL': 'BRL: Brazilian Real',
  'HUF': 'HUF: Hungarian Forint',
  'DKK': 'DKK: Danish Krone',
  'JPY': 'JPY: Japanese Yen',
  'ILS': 'ILS: Israeli New Shekel',
  'TRY': 'TRY: Turkish Lira',
  'RON': 'RON: Romanian Leu',
  'GBP': 'GBP: British Pound Sterling',
  'PHP': 'PHP: Philippine Piso',
  'HRK': 'HRK: Croatian Kuna',
  'NOK': 'NOK: Norwegian Krone',
  'ZAR': 'ZAR: South African Rand',
  'MXN': 'MXN: Mexican Peso',
  'AUD': 'AUD: Australian Dollar',
  'USD': 'USD: United States Dollar',
  'KRW': 'KRW: South Korean won',
  'HKD': 'HKD: Hong Kong Dollar',
  'EUR': 'EUR: European Union Euro',
  'ISK': 'ISK: Icelandic Krona',
  'CZK': 'CZK: Czech Koruna',
  'THB': 'THB: Thai Baht',
  'MYR': 'MYR: Malaysian Ringgit',
  'NZD': 'NZD: New Zealand Dollar',
  'PLN': 'PLN: Polish Zloty',
  'CHF': 'CHF: Swiss Franc',
  'SEK': 'SEK: Swedish Krona',
  'CNY': 'CNY: Chinese Yuan',
  'SGD': 'SGD: Singapore Dollar',
  'INR': 'INR: Indian Rupee',
  'IDR': 'IDR: Indonesian Rupiah',
  'RUB': 'RUB: Russian Ruble'
};

export default currencies;