const flagicons = {
    'CAD': 'flag-icon-ca',
    'BGN': 'flag-icon-bg',
    'BRL': 'flag-icon-br',
    'HUF': 'flag-icon-hu',
    'DKK': 'flag-icon-dk',
    'JPY': 'flag-icon-jp',
    'ILS': 'flag-icon-il',
    'TRY': 'flag-icon-tr',
    'RON': 'flag-icon-ro',
    'GBP': 'flag-icon-gb',
    'PHP': 'flag-icon-ph',
    'HRK': 'flag-icon-hr',
    'NOK': 'flag-icon-no',
    'ZAR': 'flag-icon-za',
    'MXN': 'flag-icon-mx',
    'AUD': 'flag-icon-au',
    'USD': 'flag-icon-us',
    'KRW': 'flag-icon-kr',
    'HKD': 'flag-icon-hk',
    'EUR': 'flag-icon-eu',
    'ISK': 'flag-icon-is',
    'CZK': 'flag-icon-cz',
    'THB': 'flag-icon-th',
    'MYR': 'flag-icon-my',
    'NZD': 'flag-icon-nz',
    'PLN': 'flag-icon-pl',
    'CHF': 'flag-icon-ch',
    'SEK': 'flag-icon-se',
    'CNY': 'flag-icon-cn',
    'SGD': 'flag-icon-sg',
    'INR': 'flag-icon-in',
    'IDR': 'flag-icon-id',
    'RUB': 'flag-icon-ru'
}


export default flagicons;